name: Convert

on:
  workflow_dispatch

jobs:
  build:
    name: Convert
    runs-on: macos_latest
    steps:
      - uses: actions/checkout@v4
      - name: Set values
        run: |
            cat config >> "$GITHUB_ENV"
      - name: Convert
        run: |
            [ $app_name ] && xcrun safari-web-extension-converter ./extension --project-location ./safari-extension --force --no-open --app-name "$app_name"
      - name: Build
        run: |
            [ $app_name ] && xcodebuild -project "./safari-extension/$app_name/$app_name.xcodeproj" -scheme "$app_name (macOS)" -arch x86_64 -configuration Debug clean build CONFIGURATION_BUILD_DIR=./safari-extension-build
      - name: Prepare App for Upload
        run: |
            [ $app_name ] && /bin/mv "./safari-extension/$app_name/safari-extension-build/$app_name.app" ./build.app
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build.app
          path: build.app
